# Generated by Django 3.0.6 on 2020-05-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20200505_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='format',
        ),
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.Format'),
        ),
        migrations.AlterField(
            model_name='format',
            name='name',
            field=models.CharField(help_text='Ingrese el formato del archivo del libro', max_length=200),
        ),
    ]
