# Generated by Django 3.0.5 on 2020-06-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='estado',
            field=models.CharField(blank=True, choices=[(1, 'Distrito Capital'), (2, 'Amazonas'), (3, 'Anzoátegui'), (4, 'Apure'), (5, 'Aragua'), (6, 'Barinas'), (7, 'Bolívar'), (8, 'Carabobo'), (9, 'Cojedes'), (10, 'Delta Amacuro'), (11, 'Falcón'), (12, 'Guárico'), (13, 'Lara'), (14, 'Mérida'), (15, 'Miranda'), (16, 'Monagas'), (17, 'Nueva Esparta'), (18, 'Portuguesa'), (19, 'Sucre'), (20, 'Táchira'), (21, 'Trujillo'), (22, 'Vargas'), (23, 'Yaracuy'), (24, 'Zulia')], default=1, max_length=80, null=True),
        ),
    ]
